# Generated by Django 6.0.6 on 2026-07-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="Disponibilidad para recibir domicilios (solo aplica a domiciliarios).",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[("cliente", "Cliente"), ("domiciliario", "Domiciliario")],
                default="cliente",
                max_length=20,
            ),
        ),
    ]
