# Generated by Django 6.0.6 on 2026-07-08 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0004_domicilio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='products',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domicilio', to='sells.order'),
        ),
    ]
