# Generated by Django 6.0.6 on 2026-07-08 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0005_remove_domicilio_products_domicilio_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('productos_vendidos', models.TextField()),
                ('total', models.FloatField()),
                ('orden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sells.order')),
            ],
        ),
    ]
