# Generated by Django 6.0.6 on 2026-07-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0006_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
