# Generated by Django 6.0.6 on 2026-07-29 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sells", "0007_alter_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="domicilio",
            name="domiciliario",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "domiciliario"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domicilios_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("recibido", "Recibido"),
                    ("en_preparacion", "En preparación"),
                    ("listo", "Listo"),
                    ("entregado", "Entregado"),
                ],
                default="recibido",
                max_length=20,
            ),
        ),
    ]
