# Generated by Django 6.0.6 on 2026-07-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sells", "0008_domicilio_domiciliario_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("hamburguesas", "Hamburguesas"),
                    ("pizzas", "Pizzas"),
                    ("perros_calientes", "Perros Calientes"),
                    ("bebidas", "Bebidas"),
                    ("postres", "Postres"),
                    ("otros", "Otros"),
                ],
                default="otros",
                max_length=30,
            ),
        ),
    ]
