# Generated by Django 6.0.6 on 2026-07-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sells", "0009_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="domicilio",
            name="entregado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="domicilio",
            name="evidencia_entrega",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Foto de evidencia de entrega, guardada como data URI.",
            ),
        ),
    ]
